In [1]:
import numpy as np
import pandas as pd

integer array

In [5]:
L3 = np.array([3.14, 4, 2, 3])
print(L3)

[3.14 4.   2.   3.  ]


Create a length-10 integer array filled with zeros

In [6]:
L4 = np.zeros(10, dtype=int)
print(L4)

[0 0 0 0 0 0 0 0 0 0]


Create a 3x5 floating-point array filles with 1s

In [7]:
L5 = np.ones((3, 5), dtype=float) 
print(L5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Create a 3x5 array filled with 3.14

In [8]:
L6 = np.full((3,5), 3.14)
print(L6)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


Create an array filled with a linear squence<br>
String ar 0, ending at 20, steeping by 2<br>
this is similar to th4e built-in range() function

In [9]:
print(np.arange(0, 20, 2))

[ 0  2  4  6  8 10 12 14 16 18]


Create an array of five values evenly spaced between 0 and 1

In [10]:
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


Create a 3x3 array of uniformly distributed <br>
random values between 0 and 1

In [11]:
print(np.random.random((3, 3)))

[[0.10221171 0.24355232 0.27187759]
 [0.97586207 0.75347399 0.06492978]
 [0.55756137 0.96757804 0.9247118 ]]


Create a 3x3  array of narmally distrubute random values
with mean 0 and standard deviation 1

In [13]:
print(np.random.normal(0, 1, (3, 3)))

[[ 0.73790463 -2.46234487  2.90351414]
 [-0.27287501 -1.11901601  0.764879  ]
 [ 0.82800986  0.6205542   1.71893822]]


Create a 3x3 identity matrix

In [14]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create an uninitialized array of three <br>
The values will be whatever happens to already ecist at that memory location

In [15]:
print(np.empty(3))

[1. 1. 1.]


seed for reproducibility<br>
seed : By specifying a seed, it is possible to fix the random number to be generated in advance. <br>
This is used when reproducibility is required in analysis or processing that uses random numbers.

In [16]:
x1 = np.random.randint(10, size=6)            #One-dimensional array
x2 = np.random.randint(10, size=(3, 4))       #Two-dimensional array
x3 = np.random.randint(10 ,size=(3, 4, 5))    #Three-dimensioanl array

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array)

In [17]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


Another useful attribute is the dtype, the data type of the array 

In [18]:
print("dtype:", x3.dtype)

dtype: int64


Other attributes include itemsize, which lists the size (in bytes) of each array element, and nbytes, which lists the total size (in bytes) of the array<br>
In general, we expect that nbytes is equal to itemsize times size.

In [19]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data.<br>
This is one area in which NumPy array slicing differs from Python list slicing　
in lists, slices will be copies.<br>

In [20]:
print(x2)

[[4 9 2 7]
 [0 6 0 9]
 [5 5 8 5]]


Let's extract a $2 \times 2$ subarray from this:

In [22]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[4 9]
 [0 6]]


Now if we modify this subarray, we'll see that the original array is changed!
This default behavior is actually quite useful.<br>
it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.<br>

In [31]:
x2_sub[0, 0] = 99
print(x2_sub)
print(x2)

[[99  9]
 [ 0  6]]
[[99  9  2  7]
 [ 0  6  0  9]
 [ 5  5  8  5]]


# Reshaping of Arrays

Another useful type of operation is reshapring of arrays.<br>
The most flexible way of doing this is with the reshpe method.<br>
Note that for this to work, the size of the initial array must match the size of the reshaped array.<br> 
Where possible, the reshape method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.<br>

In [24]:
grid = np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. <br>
This can be done with the reshape method, or more easily done by making use of the newaxis keyword within a slice operation:

In [25]:
x = np.array([1, 2, 3])

row vector via reshape

In [26]:
print(x.reshape((1, 3)))

[[1 2 3]]


row vector via newaxis

In [27]:
print(x[np.newaxis, :])

[[1 2 3]]


column vector via reshape

In [28]:
print(x.reshape((3, 1)))

[[1]
 [2]
 [3]]


column vector via newaxis

In [30]:
print(x[:, np.newaxis])  

[[1]
 [2]
 [3]]


# Reshaping of Arrays

all of the preceding routines worked on single arrays. <br>
It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those oprations here:

In [32]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once

In [33]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:

In [34]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

In [36]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [37]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack(vertical stack) and np.hstack(horizontal stack) functions:

In [38]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],[6, 5, 4]])

# vertically stack  the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [40]:
# horizontally stack the arrays
y = np.array([[99],[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Splitting of arrays

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshap method.<br>
For example, if yuou wanna put the numbers 1 through 9 in a $3\times 3$ grid, you can do the following:

In [42]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initail array must match the size of the reshaped array.<br>
Where possible, the reshape method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the comversion of a one-dimensional row or column matrix. this can be done with the reshape method, or more easily done by making use of the newaxis keyword within a slice operation:

In [44]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape([1, 3])

array([[1, 2, 3]])